stages:
    - build
    - package
    - test
    - deploy

variables:
    APP_VERSION: $CI_PIPELINE_IID

build website:
    image: node:16-alpine
    stage: build
    script:
        - npm install
        - npm run lint
        - npm run test:ci
        - npm run build
        - echo $APP_VERSION > public/version.html
    artifacts:
        paths:
            - .next
            - public
